import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<div className="bg-cover bg-center min-h-max"
    style={{ backgroundImage: "url('/yaalimadad.jpg')" }}  >
    <html lang="en">
      
      <body
        className= {`${geistSans.variable} ${geistMono.variable} antialiased ` } 
      >  
        {children}
      </body> 
    </html></div>
  );
}
